export const backgroundColors = [ // background colors used in bar graph
  'rgba(255, 99, 132, 0.2)',
  'rgba(255, 159, 64, 0.2)',
  'rgba(255, 205, 86, 0.2)',
  'rgba(75, 192, 192, 0.2)',
  'rgba(54, 162, 235, 0.2)',
  'rgba(153, 102, 200, 0.15)',
  'rgba(100, 0, 255, 0.2)',
  'rgba(150, 203, 207, 0.2)',
  'rgba(255, 0, 207, 0.15)',
];

export const borderColors = [ // border colors used in bar graph
  'rgba(255, 99, 132)',
  'rgba(255, 159, 64)',
  'rgba(255, 205, 86)',
  'rgba(75, 192, 192)',
  'rgba(54, 162, 235)',
  'rgba(153, 102, 255, 0.65)',
  'rgba(100, 100, 255)',
  'rgba(150, 203, 207)',
  'rgba(255, 0, 207, 0.65)',
];

export const graphOptions = {
  scales: {
    xAxes: [{
      scaleLabel: {
        display: true,
      }, 
      ticks: {
        fontSize: 16
      }
    }],
    yAxes: [{
      scaleLabel: {
        display: true,
        labelString: 'Song Count ',
        fontSize: 20,
      },
      ticks: {
          beginAtZero: true,
          fontSize: 20
      }
    }],
  },  
  legend: {
    display: false
  },
  title: {
    display: true,
    fontSize: 20,
    text: 'Song Count on Featured Playlists'
  },

  maintainAspectRatio: true 
}

export const buttonStyles = {
  width: '30%',
  height: '45px',
  margin: '2%',
  fontSize: '24px',
  backgroundColor: 'rgba(255, 99, 132, 0.5)',
  border: '3px solid rgba(255, 99, 132)'
}























export const songObject = {
  "1989": 1,
  "2002": 1,
  "Calling My Phone": 1,
  "Start Again": 1,
  "White Dove": 1,
  "In sight": 1,
  "einschlafen": 1,
  "Désir": 1,
  "Rojo": 1,
  "Tremoland": 1,
  "Sunrise Catrin": 1,
  "Cesia": 1,
  "Stars Above": 1,
  "The Sun Will Rise Again": 1,
  "Slowly Flying": 1,
  "Beneath": 1,
  "Rhea": 1,
  "retrospect": 1,
  "We": 1,
  "Austafjord": 1,
  "There in the Silence": 1,
  "Stream Of Consciousness": 1,
  "Trace": 1,
  "Focus": 3,
  "Here Right Now": 1,
  "Obsession": 1,
  "Frigate birds": 1,
  "Pegasus": 1,
  "Half Moon Pass": 1,
  "Awash": 1,
  "Slow Rise": 1,
  "Ambiance": 1,
  "Jamas In Heaven": 1,
  "Hvis du bare vidste": 1,
  "Equinox": 1,
  "Dream #5 [Drifting Apart]": 1,
  "Boreas": 1,
  "Painted Life": 1,
  "Without Your Love (feat. Julia Stone)": 1,
  "Long Blue Light": 1,
  "New Song": 1,
  "look up": 1,
  "Trick To Happy": 1,
  "Call Me When You Land": 1,
  "To the Mountains": 1,
  "I Was Born To Love You": 1,
  "Lose Somebody": 1,
  "Put Your Records On": 1,
  "Ocean Bed": 1,
  "Grow into Love": 1,
  "Faith Healer": 1,
  "And It's Still Alright": 1,
  "Sanctuary": 1,
  "If You Call": 1,
  "Lockdown On Date Night Tuesday": 1,
  "Fall, Fall, Fall": 1,
  "Detour": 1,
  "Santa Barbara": 1,
  "Losing You": 1,
  "As It Is": 1,
  "What A Day - Edit": 1,
  "Two": 1,
  "Good Woman": 1,
  "Pin It Down": 1,
  "Not Dead Yet": 1,
  "Count On Me": 1,
  "Used To Be Lonely": 1,
  "Yours to Keep": 1,
  "Moon in the Morning": 1,
  "Buzz": 1,
  "Pacific": 2,
  "Someday, Somewhere": 1,
  "Run It": 1,
  "Call It Dreaming": 1,
  "I Don't Wanna Lose": 1,
  "Tried to Tell You": 1,
  "Valleys (My Love)": 1,
  "Last Time": 1,
  "Cazadera": 1,
  "Curls": 1,
  "I Hear Your Song, Sweetness": 1,
  "Lemon [Feat. Sharon Van Etten]": 1,
  "In a River": 1,
  "Manifest": 1,
  "Everything I had": 1,
  "White Dress": 1,
  "Blood Wolf Moon": 1,
  "Cool Girl": 1,
  "Come In Closer": 1,
  "Way With Words": 1,
  "Blue": 1,
  "Boy With Luv (feat. Halsey)": 1,
  "Still Life (feat. Joseph)": 1,
  "Summertime Low": 1,
  "Garden Song": 1,
  "False Alarms": 1,
  "Immune": 1,
  "Cracks In The Ceiling (feat. Joseph)": 1,
  "Faith": 1,
  "Astronaut In The Ocean": 5,
  "Your Body": 1,
  "Another Story": 1,
  "Leave The Door Open": 7,
  "Montero (Call Me By Your Name)": 7,
  "Campfire": 1,
  "Two Sides": 1,
  "Held Down": 1,
  "Rapstar": 4,
  "Only Time": 1,
  "Should I": 1,
  "You Don't Know": 1,
  "Your Hero Is Not Dead": 1,
  "Tracy": 1,
  "Fck Boys": 3,
  "SOMEBODY (feat. Vory) - from the Crimson Soundtrack": 1,
  "What You Know Bout Love": 1,
  "Never Lose You": 1,
  "Surgery": 1,
  "back together": 1,
  "Already Best Friends (feat. Chris Brown)": 1,
  "Holdin Me Down": 1,
  "Life Has Changed (feat. PnB Rock)": 1,
  "Perfect": 1,
  "Whole Lotta Liquor (feat. Future & PARTYNEXTDOOR)": 1,
  "Move (feat. Saweetie)": 1,
  "Chosen (feat. Ty Dolla $ign)": 4,
  "Luv Is Dro (feat. Static Major & Bryson Tiller)": 1,
  "Questions (feat. Future)": 1,
  "Impatient (feat. Coi Leray)": 1,
  "Good Evening": 1,
  "Day One": 2,
  "Too Much": 1,
  "Dior You": 1,
  "You Got It - Remix": 1,
  "Both of Us (feat. Rick Ross & Layton Greene)": 1,
  "R&B Shit (feat. A Boogie Wit da Hoodie)": 1,
  "Love You Too (feat. Kehlani)": 5,
  "Provide (feat. Chris Brown & Mark Morrison)": 1,
  "This Side ft. Landstrip Chip": 1,
  "Feel Better (feat. Toosii)": 1,
  "Gravity (feat. Tyler, The Creator)": 6,
  "Flawed (feat. Gunna)": 4,
  "Thieves In Atlanta (feat. Coi Leray)": 1,
  "TIME FOR YOU": 1,
  "You Ain't Worth It (with 6LACK)": 1,
  "Sex Lies (feat. Lil Baby)": 1,
  "Outta Time (feat. Drake)": 1,
  "Got It All": 1,
  "Need It Back": 1,
  "On Fleek (feat. Gunna)": 1,
  "We Outta Here": 1,
  "Yes or No (feat. IV JAY)": 1,
  "2hrs": 1,
  "Mystery Lady (feat. Don Toliver)": 1,
  "Sweet Lucy": 1,
  "Wasted": 1,
  "Options (with Wale)": 1,
  "Sunblind": 2,
  "Best Friend (feat. Doja Cat": 5,
  "The Stable Song": 1,
  "21C/Delta": 1,
  "Stay High": 1,
  "More I See": 1,
  "Feels so right": 1,
  "Tyrone 2021 (feat. Big Sean)": 1,
  "Letter 2 U - Acoustic": 1,
  "None of Your Love - Bonus": 1,
  "Follow the Water": 1,
  "So Caught Up": 1,
  "Society's a Mansion": 1,
  "Lose This Number": 1,
  "Fire": 1,
  "Guess Again": 1,
  "Sugar Mama": 1,
  "Moon Juice (feat. Jeremih)": 1,
  "Mighty Soul": 1,
  "Mood Swings (feat. Lil Tjay & Summer Walker) - Remix": 1,
  "The Love": 1,
  "What Am I Here For": 1,
  "Excitement": 1,
  "Wet (feat. Mulatto) - Remix": 1,
  "Timeless Interlude": 1,
  "Is It Real - Acoustic": 1,
  "Follow (Extended Mix)": 1,
  "Distant Axis": 1,
  "C'est La Vie No.2": 1,
  "Ronda": 1,
  "The Kármán Line": 1,
  "For the Sky": 1,
  "Gloria": 1,
  "Phases": 1,
  "memories of her, last winter": 1,
  "Packard - Blomqvist & Schories Sunrise Mix": 1,
  "Sunday Travels": 1,
  "Plastic": 1,
  "Houdini": 1,
  "Nomad": 1,
  "Soul Mates": 1,
  "sundown": 1,
  "Careless": 1,
  "Pantar": 1,
  "Roots": 1,
  "Tiger Park": 1,
  "High Spirits": 1,
  "Dan": 1,
  "Favorite Sause": 1,
  "First Sip of Coffee": 1,
  "distance": 2,
  "Versailles (Hold) - Edit": 1,
  "Isthmus": 1,
  "Otherside - Edit": 1,
  "Forrest Glade": 1,
  "Blóð": 1,
  "Undecided": 1,
  "Get Down - Short Edit": 1,
  "feather light melodies": 1,
  "No Silence": 1,
  "Second Sun": 1,
  "Dunes o Dunes": 1,
  "Sumidero": 1,
  "Call For Spring": 1,
  "Midnight Somewhere": 1,
  "Feel": 1,
  "Tether": 3,
  "Unconditional Love": 1,
  "Sisu": 1,
  "Lost in Flight": 1,
  "Yuregine Deprem": 1,
  "Prietita": 1,
  "Backpack City": 1,
  "Wolfgang": 1,
  "Jasmine": 1,
  "Gloom": 1,
  "Ordel": 1,
  "show me the way": 1,
  "Unattached - Edit": 1,
  "Blue Lounge": 1,
  "Melloton": 1,
  "Awake": 1,
  "Train to Kawazu": 1,
  "Message": 1,
  "Origami": 1,
  "Afterlife": 1,
  "Calcium": 1,
  "Tell Me": 2,
  "Jiyu": 1,
  "Somewhere New": 1,
  "bringmesun": 1,
  "Heimat - TSHA Remix": 1,
  "telephones": 1,
  "Yeah": 1,
  "Aconcagua": 1,
  "Sunflower": 1,
  "Closer": 1,
  "Flight of the Mitoglider": 1,
  "Balcony Vibes": 1,
  "Tiny Sailboat": 1,
  "Escape": 1,
  "Unfold": 1,
  "Stranger Thing": 1,
  "Charlie's Whales": 1,
  "Nites": 1,
  "too close": 1,
  "Lenny in the Sea with Dolphins": 1,
  "Cherry Blossom": 1,
  "Flora": 1,
  "Oceans": 1,
  "5am in cairo": 1,
  "Samui Sunrise": 1,
  "Wellenlänge": 1,
  "Graf Zahl": 1,
  "Quarantine - Original": 1,
  "Lys (feat. Menke)": 1,
  "The Atmospheric Halo Fades Into The Blackness Of Space": 1,
  "Outgrown": 1,
  "Forget You": 1,
  "Haunt Me": 1,
  "No Room - Johannes Klingebiel Remix": 1,
  "Love We Found": 1,
  "Dreamt": 1,
  "The Tribe": 1,
  "5am": 1,
  "Neyð": 1,
  "Goldfish": 1,
  "Kidz of Tibet": 1,
  "Karma": 1,
  "Opals - Andhim Remix": 1,
  "Mandelbaum": 1,
  "Été Pluvieux": 1,
  "Cautious": 1,
  "One Grain": 1,
  "Dea Dia": 1,
  "The Clouds Silver Lining": 1,
  "No Goodbye": 1,
  "A Mindful Blues": 1,
  "Into You (feat. Fabolous)": 1,
  "Let It Go": 1,
  "We Belong Together": 1,
  "When I See U": 1,
  "Let Me Love You": 1,
  "Yo (Excuse Me Miss)": 1,
  "Where the Party At (feat. Nelly)": 1,
  "Girl": 1,
  "Foolish": 1,
  "Differences": 1,
  "Love": 1,
  "Be Without You - Kendu Mix": 1,
  "Me, Myself and I": 1,
  "How Do I Breathe": 1,
  "Thank God I Found You (feat. Joe & Nas) - Make It Last Remix Edit": 1,
  "You": 1,
  "Take You Down": 1,
  "Don't Mess With My Man (feat. Brian Casey & Brandon Casey)": 1,
  "Officially Missing You": 1,
  "U Remind Me": 1,
  "Buy U a Drank (Shawty Snappin') (feat. Yung Joc)": 1,
  "That Girl": 1,
  "So Gone": 1,
  "I Need a Girl": 1,
  "Bust Your Windows": 1,
  "He Wasn't Man Enough": 1,
  "Slow Down - 12\" Version": 1,
  "Spotlight": 1,
  "Bad Girl": 1,
  "Do You": 1,
  "No One": 1,
  "Like This (feat. Eve)": 1,
  "I Should Have Cheated": 1,
  "It's Over Now": 1,
  "Happy": 1,
  "Umbrella": 1,
  "Go On Girl": 1,
  "Soldier (feat. T.I. & Lil' Wayne)": 1,
  "Need U Bad": 1,
  "Viento Estelar": 1,
  "Beautiful Imagination": 1,
  "Nepenthe": 1,
  "Lenitivo": 1,
  "Campus": 1,
  "Sogno Illuminum": 1,
  "Sleepy Journey": 1,
  "Touha": 1,
  "Shimmering Above Clouds": 1,
  "In My Time": 1,
  "Notes": 1,
  "State of Unreality": 1,
  "Med slutna ögon": 1,
  "Endless Sky": 1,
  "Et øyeblikk": 1,
  "Sdraiata accanto a me": 1,
  "Renewal": 1,
  "Sömn": 1,
  "Kritagya": 1,
  "Purity": 1,
  "Moment To Moment": 1,
  "Arnasa": 1,
  "Hopeful": 1,
  "Sedate Dawn": 1,
  "Nattljus": 1,
  "Lost For Words": 1,
  "Old Station Atmos": 1,
  "Norm and Mirza": 1,
  "Quiet Nights": 1,
  "Cherry Tomatoes": 1,
  "Leticia": 1,
  "I Thought it would be Different this Time": 1,
  "Moments of Stillness": 1,
  "Andas": 1,
  "Sequoia": 1,
  "Radiant Dream": 1,
  "Such A Simple Thing": 1,
  "Sundown": 1,
  "Yakamoz": 1,
  "Ladybugs": 1,
  "Hovering": 1,
  "In the Gold of the Sun": 1,
  "Acércate": 1,
  "Noraezean": 1,
  "Appreciation": 1,
  "Desiderio": 1,
  "Make It Last": 1,
  "Reappearance": 1,
  "Sonhando": 1,
  "Birdcage Walk": 1,
  "Bella": 1,
  "Secrets": 1,
  "Soñando contigo": 1,
  "Lights Out": 1,
  "vindur": 1,
  "Sineway": 1,
  "Absence": 1,
  "Paper Planes": 1,
  "Miles Away": 1,
  "Rained In": 1,
  "Sweet Hangover": 1,
  "Oko marries Eb": 1,
  "Indian Summer": 1,
  "Y": 1,
  "Endless Ether": 1,
  "Becalming": 1,
  "No Sleep": 1,
  "One_4_u": 1,
  "Illa Pancha": 1,
  "Tao": 1,
  "Drag Me Down - Instrumental": 1,
  "Intermission": 1,
  "Tranquility": 1,
  "Immersed": 1,
  "Halcyon": 1,
  "Mind's Edge": 1,
  "Better Together": 1,
  "Turndown Service": 1,
  "Morning Prayer": 1,
  "Roomies": 1,
  "Separated": 1,
  "we'll stay inside when it rains": 1,
  "Life Tools": 1,
  "Medicinal Sushi": 1,
  "Suivez-moi": 1,
  "Better Days": 1,
  "Chips": 1,
  "Wanderlust": 1,
  "Céleste": 1,
  "Wish We Could Stay Like This Forever": 1,
  "Earth": 1,
  "Everything is Different": 1,
  "Arise": 1,
  "Unfolding": 1,
  "Chromatic": 1,
  "Andestus": 1,
  "What If We Met": 1,
  "Sweet Night": 1,
  "Moment Of Peace": 1,
  "Waiting for You": 1,
  "Understanding": 1,
  "Pharaoh": 1,
  "Aurora": 2,
  "City Lounge": 1,
  "1am in nyc": 1,
  "aoi": 1,
  "Aphelion": 1,
  "Solitude": 1,
  "Midnight Cruise": 1,
  "blind blossom": 1,
  "Deep Dive": 1,
  "Yoruba": 1,
  "Night Shift": 1,
  "Purple Skies": 1,
  "Querencia": 1,
  "Ruff Ryders' Anthem": 1,
  "Woo Hah!! Got You All in Check": 1,
  "Shimmy Shimmy Ya": 1,
  "Over skyerne": 1,
  "What's My Name": 1,
  "How Do You Want It (ft. KC, Jojo)": 1,
  "It's a Party (feat. Zhane)": 1,
  "Crush on You (feat. Lil' Cease) - Remix": 1,
  "Chilling Silence": 1,
  "Loungin (Who Do Ya Luv)": 1,
  "Still Not a Player (feat. Joe) - Radio Version": 1,
  "How's It Goin' Down": 1,
  "Des rêves sans fin": 1,
  "Canopy": 1,
  "Tantric Life": 1,
  "Depressurize": 1,
  "Roncudo": 1,
  "Framandi": 1,
  "Attends-moi": 1,
  "After Dusk": 1,
  "Slow Down the Night": 1,
  "Večeras": 1,
  "embrace": 1,
  "Sueno": 1,
  "Resting Peace": 1,
  "Altai": 1,
  "Dark Lights": 1,
  "Ut Ameris, Amabilis Esto": 1,
  "Tickling Sands": 1,
  "Snowdonia": 1,
  "From Within": 1,
  "Sleeping Awake": 1,
  "Closure": 1,
  "Caring": 1,
  "Buona notte": 1,
  "Stelliferous": 1,
  "Celestial Sonnet": 1,
  "Calmami": 1,
  "Anzhela": 1,
  "Covering the Sun": 1,
  "Ljusa Drömmar": 1,
  "Guitarra De Aire": 1,
  "Fernweh": 1,
  "Tu Bolero Es Mi Zamba": 1,
  "Solstice": 1,
  "Ballata per Elena bellissima (Ballade for Beautiful Elena)": 1,
  "wolkenlos": 1,
  "Sonnen Diamant": 1,
  "Impermanence": 1,
  "Le Louvre": 1,
  "It's for You Evelina": 1,
  "Peace Of Mind": 1,
  "Struna": 1,
  "Nuages": 1,
  "Salt of the earth": 1,
  "Saudade": 1,
  "Kleiner Singvogel": 1,
  "Maria": 1,
  "Die Wanderbiene": 1,
  "Bilbao": 1,
  "Zamba Para Ti": 1,
  "Morgensonne": 1,
  "Hard Knock Life (Ghetto Anthem)": 1,
  "früh am morgen": 1,
  "Everything Remains Raw": 1,
  "time stands still": 1,
  "What U See Is What U Get": 1,
  "Waterfalls": 1,
  "N.O.R.E.": 1,
  "X Gon' Give It To Ya": 1,
  "The Highland": 1,
  "Money, Power & Respect (feat. DMX & Lil' Kim)": 1,
  "Nas Is Like": 1,
  "Enrejado": 1,
  "ATLiens": 1,
  "Smile": 1,
  "Slippin'": 1,
  "Lavender Fields": 1,
  "Me And My Crazy World": 1,
  "Ghetto Supastar (That is What You Are) (feat. Ol' Dirty Bastard & Mýa)": 1,
  "Who Dat": 1,
  "Viola": 1,
  "Da Rockwilder": 1,
  "Bling Bling": 1,
  "Still D.R.E.": 1,
  "Bitch Please": 1,
  "Don't Belong Anywhere": 1,
  "How To Rob": 1,
  "Horse & Carriage (feat. Mase)": 1,
  "Holla Holla": 1,
  "Silberberg": 1,
  "Make 'Em Say Ugh": 1,
  "Shut Up (feat. Duece Poppito of 24 Karatz, Trina, & Co of Tre +)": 1,
  "Triumph (feat. Cappadonna)": 1,
  "Cell Therapy": 1,
  "Lola": 1,
  "Joints & Jam": 1,
  "Da B Side (feat. The Notorious B.I.G.)": 1,
  "How Ya Livin' featuring Nas": 1,
  "Guahara": 1,
  "Definition": 1,
  "Discipline": 1,
  "Alla En El Mar": 1,
  "Lost in the North Sea": 1,
  "Nostalgia": 1,
  "Die einsame Zypresse": 1,
  "Caricia": 1,
  "tranquilas noches valencianas": 1,
  "Napoli": 1,
  "My Hidden Treasure": 1,
  "San Sebastien": 1,
  "Jobim: Road to the Sun": 1,
  "Wunder der Welt": 1,
  "Serra Calderona": 1,
  "Mittenwald": 1,
  "Davos": 1,
  "Through the canyon": 1,
  "My Name Is": 1,
  "Zirbenwald": 1,
  "New York, New York": 1,
  "Gettin' It": 1,
  "Dormi Bene": 1,
  "The Pioneers": 1,
  "By Myself but Not Alone": 1,
  "Llamame e Insiste": 1,
  "I Want It All (feat. Mack 10)": 1,
  "Forgive You": 1,
  "Saas Fee": 1,
  "(What's So Funny 'Bout) Peace, Love and Understanding?": 1,
  "Regenbogen": 1,
  "Esperare": 1,
  "Lilacs": 1,
  "Requiem": 1,
  "Lonely in London": 1,
  "Aneto": 1,
  "Cordon Bleu": 1,
  "Das Kaleidoskop": 1,
  "Serenity": 1,
  "sunflower": 1,
  "Vignemale": 1,
  "Die ersten Zugvögel": 1,
  "Opulence": 1,
  "Circulatory": 1,
  "Cerbillona": 1,
  "bom futuro": 1,
  "Saana": 1,
  "Spirited Away": 1,
  "Siena": 1,
  "Safran": 1,
  "Bacoli": 1,
  "Memento": 1,
  "Vanja": 1,
  "Come Fly With Me Honey": 1,
  "Clementia": 1,
  "Florence": 1,
  "Bosque Nevado": 1,
  "Tres Sonatas VIII": 1,
  "Cassandra": 1,
  "Detener El Tiempo A Tu Lado": 1,
  "Dicen": 1,
  "Deukmejian": 1,
  "Märk Hur Vår Skugga": 1,
  "Tisu": 1,
  "Venezia": 1,
  "Bolero Del Sur": 1,
  "Amor a la distancia": 1,
  "Shifrin": 1,
  "Milagro": 1,
  "Eternal Flame Falls": 1,
  "No One To Talk To": 1,
  "Floresta": 1,
  "Der Feder Waltzer": 1,
  "Hoe kan dit geen liefde zijn?": 1,
  "De Tu Mano": 1,
  "lago azul": 1,
  "The Big Apple": 1,
  "Un Dia de Novembre": 1,
  "Something Beautiful": 1,
  "Lagrima": 1,
  "Con calma": 1,
  "Consuelo": 1,
  "Siempre Estoy Pensando En Ti": 1,
  "Cantabile": 1,
  "Was It Something I Said": 1,
  "YKWIM?": 1,
  "Hot Rod": 1,
  "Are You Bored Yet? (feat. Clairo)": 1,
  "The Loser": 1,
  "Cotton Candy": 1,
  "Maple Syrup Tears": 1,
  "the village": 1,
  "Can I Call You Tonight?": 1,
  "Something, in General": 1,
  "I'll Be There For You/You're All I Need To Get By - Puff Daddy Mix": 1,
  "Ten Crack Commandments - 2014 Remaster": 1,
  "Fu-Gee-La": 1,
  "Think About It": 1,
  "Left, Right, Left": 1,
  "I'll Be": 1,
  "Find a Way": 1,
  "THE BOTTOM": 1,
  "4EVER": 1,
  "Goodie Bag": 1,
  "OUTTA MY MIND": 1,
  "Life Inside": 1,
  "Lonely": 1,
  "JENN!FER AN!STON": 1,
  "New Flesh": 1,
  "Metamodernity": 1,
  "All I Need": 1,
  "Pretty Girl": 1,
  "Habit": 1,
  "Homage": 1,
  "Kids": 1,
  "That I Miss You": 1,
  "Flaming Hot Cheetos": 1,
  "80's High School": 1,
  "Chandelier": 1,
  "Cooks": 1,
  "How Was Your Day?": 2,
  "Tommy's Party": 1,
  "Harvard": 1,
  "Shh": 1,
  "Hello?": 1,
  "Sunset Wife": 1,
  "Punching Bag": 1,
  "Lava": 1,
  "Medicine": 1,
  "My Jinji": 1,
  "Hey Lover!": 1,
  "Cool to You": 1,
  "Don't Trust Me": 1,
  "80's makeout session": 1,
  "Frank Said": 1,
  "I'll Be Around": 1,
  "Perks of Being a Sunflower": 1,
  "Lucy": 1,
  "I Love You So": 1,
  "Telephone": 1,
  "Turtleneck Sweater": 1,
  "Never Had The Balls": 1,
  "Bends": 1,
  "Six Speed": 1,
  "Shy": 1,
  "Needs": 1,
  "Baby Baby": 1,
  "Morning Sex": 1,
  "Reverse Cowgirl": 1,
  "Paul": 1,
  "Here I Found / No Self Control": 1,
  "Next Best Thing": 1,
  "Loving Is Easy": 1,
  "Thunder": 1,
  "Car Crash in G Major": 1,
  "Peach Pit": 1,
  "Disappear": 1,
  "Prune, You Talk Funny": 1,
  "Sinatra": 1,
  "Dennis": 1,
  "kissing girls": 1,
  "Purple Haze": 1,
  "Honeypie": 1,
  "Dark Red": 1,
  "East Coast": 1,
  "She Plays Bass": 1,
  "Marigold": 1,
  "My Own Person": 1,
  "Do U Mind? (Leave the Light On)": 1,
  "Fool": 1,
  "girls": 1,
  "Olive Juice": 1,
  "Someone To Spend Time With": 1,
  "Burger King Bathroom": 1,
  "kiss u better": 1,
  "Antidote": 1,
  "Avery": 1,
  "Velvet Light": 1,
  "Heaven": 1,
  "Mystery": 1,
  "Birch Tree": 1,
  "Seabirds": 1,
  "Sore Throat": 1,
  "Boy, I'm Just a Loser for Your Love": 1,
  "Everytime": 1,
  "Falling for U": 1,
  "Sunnnn": 1,
  "Oh Klahoma": 1,
  "Sometimes (Backwood)": 1,
  "I DONT KNOW ABOUT HIM": 1,
  "Rain On The Cobblestone": 1,
  "Tormenta ligera": 1,
  "Pouring Rain And Thunder": 1,
  "Take Cover": 1,
  "Peaceful Weather": 1,
  "Cozier Rain": 1,
  "Pluie toute la nuit": 1,
  "Rainy Misty Skies": 1,
  "Soft Spring Rain": 1,
  "Pouring Thunderstorm": 1,
  "Raining After Midnight": 1,
  "Cozy Rain": 1,
  "Spring Rain": 1,
  "Nature Collection": 1,
  "Thunderstorm In the Forest": 1,
  "Hard Rain Falling": 1,
  "Midwinter Downtown Rain": 1,
  "Focus Bad Weather": 1,
  "Calming Rain Deluxe": 1,
  "Rain All Year Round": 1,
  "Relaxation Rain Sound": 1,
  "Non Stop Rain Sounds": 1,
  "Stormy Thunder": 1,
  "Continuous Rain": 1,
  "Rain White Noise": 1,
  "Rain all day": 1,
  "Night Storm": 1,
  "Rumbling": 1,
  "Cosy Storm": 1,
  "Dark Storm": 1,
  "Stormy Weather": 1,
  "Muffled Thunder": 1,
  "Rainy Stoop": 1,
  "Storm Through The Night": 1,
  "Rainy Nights": 1,
  "Fjorgyn": 1,
  "Lluvia calmante": 1,
  "Light Crispy Rain": 1,
  "Relaxing Rain Sound For Sleep": 1,
  "Relaxing Rain Slumber": 1,
  "Soothing Rain Sounds": 1,
  "Thunder And Lightning": 1,
  "The Mystique Sounds Of Nature": 1,
  "Let It Rain": 1,
  "Mother Nature's Call": 1,
  "Never-ending Rain": 1,
  "Rain": 1,
  "mid day rain": 1,
  "Tormenta de lluvia de la selva": 1,
  "Ocean Rain": 1,
  "Under The Roof": 1,
  "Mediatative Rain": 1,
  "Mindful Rain": 1,
  "Stratiform Rain": 1,
  "Starting to rain": 1,
  "Fall Rain Recording": 1,
  "Medium to Heavy Rain": 1,
  "Steady Rain": 1,
  "Struck by lightning": 1,
  "Fall asleep Storm": 1,
  "Rain Sky Samples 1": 1,
  "Sky Diamonds": 1,
  "It's gonna rain all night": 1,
  "Distant Storm": 1,
  "Rain Window": 1,
  "Light Rain - Distant Thunder": 1,
  "Rain Shower & Thunder": 1,
  "Deep Rain Thunder": 1,
  "Trueno distante": 1,
  "Thunder & Pouring Rain": 1,
  "Storm Ahead": 1,
  "Rain Coming In": 1,
  "Storms": 1,
  "Tormenta de la selva": 1,
  "Gentle Thunderstorm": 1,
  "Eye Of The Storm": 1,
  "Lets Let the Rain Fall": 1,
  "Shelter From Rain And Thunder": 1,
  "Calm Evening Rain": 1,
  "Morning Rain": 1,
  "Exotic Rain": 1,
  "Dense Rainfall": 1,
  "Distant Thunder": 1,
  "Juicy Rain": 1,
  "Raining Down": 1,
  "Scandinavian Rain": 1,
  "Raining On Metal": 1,
  "Under Shelter Rainstorm": 1,
  "Calm Rain, Thunder": 1,
  "Soft Rain": 1,
  "Sleep Soft Rain": 1,
  "Rain Falling From the Sky": 1,
  "Massive Rainfall": 1,
  "Thunder and Storm": 1,
  "Tuck You In Rain": 1,
  "Park Rain, Pt 3": 1,
  "The Sky's Crying": 1,
  "Soothing Rain": 1,
  "Relaxing Thunderstorm": 1,
  "Monster (Shawn Mendes & Justin Bieber)": 1,
  "Be Kind (with Halsey)": 1,
  "Don't Start Now": 1,
  "Dynamite": 1,
  "Savage Love (Laxed - Siren Beat)": 1,
  "ROCKSTAR (feat. Roddy Ricch)": 1,
  "Anyone": 1,
  "willow": 1,
  "Head & Heart (feat. MNEK)": 1,
  "Lose You To Love Me": 1,
  "Adore You": 1,
  "Beautiful People (feat. Khalid)": 1,
  "Call You Mine": 1,
  "fuck, i'm lonely": 1,
  "Intentions": 1,
  "If I Can't Have You": 1,
  "Before You Go": 1,
  "10,000 Hours (with Justin Bieber)": 1,
  "If the World Was Ending - feat. Julia Michaels": 1,
  "i'm so tired...": 1,
  "Take You Dancing": 1,
  "Rain On Me (with Ariana Grande)": 1,
  "How Do You Sleep?": 1,
  "Watermelon Sugar": 1,
  "Lonely (with benny blanco)": 1,
  "Make It Right (feat. Lauv)": 1,
  "Break My Heart": 1,
  "cardigan": 1,
  "comethru": 1,
  "Without Me": 1,
  "Memories": 1,
  "boyfriend (with Social House)": 1,
  "Never Really Over": 1,
  "It's You": 1,
  "Someone You Loved": 1,
  "I Don't Care (with Justin Bieber)": 1,
  "Circles": 1,
  "Hate Me (with Juice WRLD)": 1,
  "The Man": 1,
  "Yellow Hearts": 1,
  "Falling": 1,
  "Youngblood": 1,
  "Yummy": 1,
  "Kings & Queens": 1,
  "Sucker": 1,
  "Who Do You Love": 1,
  "Heather": 1,
  "hot girl bummer": 1,
  "Find U Again (feat. Camila Cabello)": 1,
  "Dancing With A Stranger (with Normani)": 1,
  "Sunday Best": 1,
  "The Middle": 1,
  "Supalonely": 1,
  "Señorita": 1,
  "thank u, next": 1,
  "Let Me Down Slowly": 1,
  "This Feeling": 1,
  "Paradise": 1,
  "Eastside (with Halsey & Khalid)": 1,
  "The Bones": 1,
  "my ex's best friend (with blackbear)": 1,
  "Say So": 1,
  "You Need To Calm Down": 1,
  "lovely (with Khalid)": 1,
  "Here With Me": 1,
  "7 rings": 1,
  "Alone, Pt. II": 1,
  "Saturday Nights": 1,
  "Beautiful (feat. Camila Cabello)": 1,
  "Dusk Till Dawn - Radio Edit": 1,
  "Sit Still, Look Pretty": 1,
  "Let Go": 1,
  "FILO": 1,
  "High Beliefs": 1,
  "W.E.": 1,
  "Atmos Eleven": 1,
  "Polaris": 1,
  "Centered": 1,
  "The Forest": 1,
  "Vivante": 1,
  "Magic": 1,
  "Arriving": 1,
  "Sunset": 1,
  "One Path": 1,
  "Dark Waters": 1,
  "Furlong Shams": 1,
  "Crystal Caves": 1,
  "Waiting": 1,
  "Starseed": 1,
  "Kaip Angelai": 1,
  "Cloches d'Arbres": 1,
  "With the Moon Behind": 1,
  "Forest Canvas": 1,
  "Pure Air": 1,
  "Contemplation": 1,
  "In Bloom": 1,
  "Goldbrick": 1,
  "Reach For the Sky": 1,
  "Faultless": 1,
  "Te Urewera": 1,
  "KSM66": 1,
  "Philadelphia Shore": 1,
  "Crossing Paths": 1,
  "Hearts of Toby": 1,
  "Serenità": 1,
  "I Will Carry You": 1,
  "Slow Down": 1,
  "Light The Dark": 1,
  "Inocybe": 1,
  "Gentle Awakening": 1,
  "As The Light Slowly Fades": 1,
  "Houd me vast": 1,
  "Tranquil": 1,
  "Blua Aero": 1,
  "Emerald Isles": 1,
  "Graduation": 1,
  "Cool Air": 1,
  "Huitussi": 1,
  "Moving On": 1,
  "Vi møtes igjen": 1,
  "Awake At Last": 1,
  "Crystal Rainbow": 1,
  "Haze": 1,
  "Eyes of Redemption": 1,
  "Ambi 25": 1,
  "Encounters": 1,
  "Resonatic": 1,
  "Journey Within (432hz) - Without Ambience": 1,
  "Deep In Love": 1,
  "Shake It Off": 1,
  "Then We Danced": 1,
  "Soothing White Noise": 1
}